### ISSUE TITLE
Old versions are still present on npm

### ISSUE THREAD

**Issue by mindywhitsitt** [blackboard/protractor-sync#16]
The npm registry has:

```
{ modified: '2017-06-06T17:25:41.789Z',
     created: '2017-05-15T19:14:12.018Z',
     '1.0.4': '2017-05-15T19:14:12.018Z',
     '1.0.5': '2017-05-16T14:40:25.425Z',
     '5.1.2': '2017-05-26T17:16:17.506Z',
     '5.1.3': '2017-06-05T02:36:22.151Z',
     '5.1.4': '2017-06-05T17:42:20.996Z',
     '5.0.0': '2017-06-06T17:25:41.789Z' },
```

It's confusing to select which version to use, and using something like `^5.0.0` might "upgrade" you to an older version unexpectedly.

**Comment by shermaneric** [comment]
Hey gang, 
It's strange that ```https://www.npmjs.com/package/protractor-sync``` shows 5.0.0. as the latest of only 3 revisions.  I thought I had run npm unpublish for at least those "old" 5.1.x versions.  I'll see if there's something I missed...

**Comment by mindywhitsitt** [comment]
Did you see the docs on `npm unpublish` which mention you can only unpublish versions published in the last 24 hours if you're using the default registry (which I assume we are)? https://docs.npmjs.com/cli/unpublish

I'm not sure why npmjs.com is only showing 'latest of 3 versions'.

**Comment by mindywhitsitt** [comment]
You can replicate this behavior locally by typing `npm view protractor-sync` into a terminal window.

**Comment by shermaneric** [comment]
Got it. Much thanks.
I'm thinking the next step is to contact support@npmjs.com as per those instructions to see if we can get the 5.1.x versions removed. Thoughts?

**Comment by scriby** [comment]
That works, or another option if you're feeling antisocial would be to abandon protractor-sync and rename to protractor_sync :)

**Comment by mindywhitsitt** [comment]
I think @steeltomato said that the `-` is more the "npm way" than the `_`...

**Comment by shermaneric** [comment]
Thanks @scriby and @mindywhitsitt for the help!
Without further delay, here is a rough draft of what I was planning to send to npmjs support.  Comments welcome!


------

Dear Node Community:

Thank you for all of your hard work and support!

We have a npm package https://www.npmjs.com/package/protractor-sync that we have recently open sourced.  While currently there are no other known consumers of the package, the future goal is to message the interested community members that this package can be widely used.

That being said, we had gone back and forth with how we were versioning our package as we moved to open source.  In the end, we decided that we wanted to mirror the major versioning of the protractor npm package (version 5) and start clean from there (5.0).  

The issue is that there has been some previous 5.1.X versions that had been already published.  Therefore, we went ahead and ran npm unpublish specifically on the following versions:

5.1.2
5.1.3
5.1.4

After doing this we noticed that our protractor-sync area on npmjs is reporting 5.0.0 as the latest of 3 versions (that's good).  However, when running npm view protractor-sync from the command line, we are still seeing the above 5.1.X versions listed.

When reading further on npm unpbulish, it was mentioned that we needed to contact npmjs support if the package version was older than 24 hours.  Specifically, we would like to request a permanent removal of protractor-sync versions 5.1.2, 5.1.3, and 5.1.4 from the npm registry if at all possible.

Let us know if there are any questions.  Thanks again for all of your help!

Eric Sherman
eric.sherman@blackboard.com

**Comment by mindywhitsitt** [comment]
That should work.

**Comment by shermaneric** [comment]
Alrighty. Message sent.  Hopefully we'll hear some good news soon.

**Comment by shermaneric** [comment]
Ok, here's what I got from the npm team.
It appears that we're ok with the above.  The only caveat being that whenever we get there it sounds like the response is saying we couldn't re-use "5.1.2, 5.2.3, or 5.1.4" when we got to it?  I replied for clarification.

------

Kiera Manion-Fischer (npm)
Jun 13, 17:02 PDT

Hi Eric,

Thanks for reaching out! You've successfully unpublished those individual versions. That shouldn't be possible under our unpublish policy, looks like that's a bug.

npm view will always still show those version numbers, but the versions been removed from the registry.

One way to test this is by trying to install one of the versions.

Unfortunately, there is no longer any way to re-use a  version of a package in the npm registry, even if it's been unpublished. The reason for this is that various systems rely on "name@version" being a unique identifier, and start throwing security warnings if the shasum changes.

While this policy is inconvenient in situations like yours, it also closes a very significant potential security vulnerability if any part of the registry infrastructure is ever compromised, without asking humans to keep track of opaque shasums themselves.

For this reason, we recommend bumping the "patch" version for even the most trivial updates.

Let me know if you have further questions,

Kiera
Tech Support
npm, Inc

**Comment by shermaneric** [comment]
sorry, in my rookie github "close", I wasn't aware that meant close the issue - i thought it just closed the box.

**Comment by shermaneric** [comment]
Ok, I just heard back.  5.1.2 / 5.1.3 / 5.1.4 are also available to use going forward.  I think we got "lucky" as we were able to unpublish versions > 24 hours old.    @all - let me know if any more issues here?   Otherwise, @mindywhitsitt I think we're cool to close the ticket.
much thanks.

**Comment by mindywhitsitt** [comment]
> 5.1.2 / 5.1.3 / 5.1.4 are also available to use going forward.

^ I'm confused. The response from NPM was:

> Yes, you've unpublished those versions: (5.1.2, 5.1.3 and 5.1.4) and they cannont be re-used.

**Comment by ghost** [comment]
Ah right, scratch that last comment of mine then.  While there's no risk on pulling an old 5.1.x version, we won't be able to use 5.1.2, 5.1.3 or 5.1.4 going forward.  (EDIT: sorry I had signed in with a different email earlier, i'll use shermaneric going forward :) )

**Comment by shermaneric** [comment]
After talking off channel, we thought it best to avoid confusion and iterate on 5.1.5.  The latest changes in /develop reflect this, 5.1.5 tag has been pushed and 5.1.5 has been published to https://www.npmjs.com/package/protractor-sync

**Comment by mindywhitsitt** [comment]
@scriby will that work out okay for you?

**Comment by scriby** [comment]
Yeah sounds good
